### ISSUE TITLE
Systems Analyst

### ISSUE THREAD

**Issue by HillbergBerk** [HackRegina/jobs#117]
<!-- 

Hillberg & Berk - Systems Analyst - Regina 
==============================================================
H&B is currently looking for a Systems Analyst to join our team! Do you have strong analytical skills, with a passion for conducting business and systems process analysis and design in a purpose-driven entrepreneurial environment? If so, our remote Systems Analyst role may be the role for you! 

Are you the right fit?

We are looking for someone who embraces their authenticity and believes in the empowerment of others and themselves – you work hard towards your goals and continually set new ones for yourself. 

You're process oriented with strong project management skills who can utilize their systems experience to enhance our current operations. You have the ability to successfully manage multiple tasks and have a strong focus on delivering exceptional customer service. 

What can you expect in this role?

As the Systems Analyst, you will lead improving business processes and productivity. You will undertake a current state capability assessment and provide recommendations on enhancements.  In becoming the resident expert in our ERP, financial, and web commerce platform you will work close with users across the business to investigate product issues, manage the vendor relationships and ongoing support, and work with end users to effectively implement new features.

In this role, you will identify, analyze, recommend, and implement appropriate system enhancements and services that will improve existing information systems, mitigate or eliminate risk, and improve business processes and productivity. You will develop user test cases and validate test results as well as perform functional testing, validate integrity of data across multiple platforms, and investigate data quality issues to determine causes and recommend solutions.

As the Systems Analyst, you will design and develop training plans and training materials to employees and create Standard Operating Procedures (SOPs) and workflow processes. You will work directly with the vendor’s technical support centres to resolve product issues and communicate with internal stakeholders of varying technical ability.

What do you need to apply?

You will have a Bachelor's Degree in Computer Science or Business Administration and 2-3 years of related experience working with enterprise applications, preferably in retail or a manufacturing environment. You have knowledge of functional analysis, quality assurance, and change management practices and strong interpersonal, time management and communication skills. Strong knowledge in the use of enterprise resource planning applications is required and experience with using Application Programming Interface (APIs) is considered an asset.
 
At Hillberg & Berk, we offer competitive cash compensation and benefits, short term incentives as well as discounts on jewellery. You will be empowered to own your career and be a part of a growing, dynamic and evolving company.

If this position sounds like it is a fit for you, apply online by July 4th, 2022. We would love to hear frpm you!

- [x ] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [ ] Salary

**Comment by LukeTowers** [comment]
?

**Comment by ryan4664** [comment]
Hey @HillbergBerk , looks like you might need a hand posting some information with the job. Let me know if I can help 👍

**Comment by HillbergBerk** [comment]
@ryan4664 help would be great! Clearly my tech skills are lacking - hence why we are interested in hiring a Systems Analyst LOL
