### ISSUE TITLE
AGT Foods - Software Developer (Back end) - Regina, SK

### ISSUE THREAD

**Issue by AGTRyanGeorge** [HackRegina/jobs#25]
### Salary Expectation
- Dependent on qualifications and experience
- Full Time, permanent

### Location
- Regina, Saskatchewan

## What You'll Do
You will be working as part of a small team developing new and maintaining existing web applications used by both internal employees and external users.  You will be developing responsive web applications in an Agile/Iterative approach.  Since we are a small team, you will be expected to be self-motivated, work well with a minimal supervision, and to be able to work directly with subject matter experts.  Depending your skills and your areas of interest, there will be opportunities to contribute in a variety of other related areas.

### Must Have
- Experience building web applications and APIs using PHP7+
- Experience with modern PHP frameworks such as Laravel or Symfony
- Experience consuming RESTful web services
- Comfortable with SQL
- Familiarity with regression/acceptance testing.

### Nice to Have
- Experience with modern front-end frameworks (Vue.js, React, Angular)
- Experience with SQL and database performance tuning.
- Strong understanding of Git (Bitbucket) or other version control systems
- Experience dealing directly with end users and/or business analysts to design solutions.
- Experience in working effectively with a minimum of supervision
- Knowledge of CI/CD pipelines
- Knowledge of agricultural systems

## About Our company
AGT Foods (www.agtfoods.com) is one of the largest suppliers of value-added pulses, staple foods and food ingredients in the world. We buy lentils, peas, beans and chickpeas from farmers around our 40+ facilities located in the best pulse growing regions in Canada, the United States, Turkey, Australia, China and South Africa and ship our products to over 120 countries around the globe.  Our Applications and Solutions development team is a small centralized team that works with our internal business analysts and users to define, build, and maintain solutions based around our internal and external Web Applications and our Microsoft Dynamics AX ERP system.

AGT Foods values and supports employment equity in the workplace.

## How to apply
Please email jobs.it@agtfoods.com with resume attached. Please include references and salary expectations.

---

## Meta
- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by lucastetreault** [comment]
Hi, can you post a salary range please?

**Comment by lucastetreault** [comment]
Closing since no salary range was provided...

**Comment by AGTRyanGeorge** [comment]
This position is now filled. Thanks!
