### ISSUE TITLE
sMedia - React Developer - Regina

### ISSUE THREAD

**Issue by jphyqr** [HackRegina/jobs#27]
### Salary Expectation

-  Based on experience
- Full Time

### Benefits

- Flexible hours
- up/down desk and pick your new work station
- the most snacks in the game
- game room
- competitive benefits package
- in-office pool table

### Location

- Regina, SK

## What You'll Do _(Job Description)_

-Own features for Vroomance.com from concept through development and implementation
-Constantly making sure we meet high-quality standards
-Creating new user experiences via React based on UI specifications
-Maintaining/improving/debugging existing code across the platform
-Write clean, well documented and well-tested code using best practices for front end development

### Must Have

-Proficiency with front-end JS frameworks (React, Angular)
-Able to work with a distributed development team, in different time zones
-Please provide github information (if available)
-Experience working in cloud-based environments
-Passion for creating an amazing user experience
-Deep understanding of the web technology stack
-Passionate about making things better

### Nice to Have

- serverless development experience (Google Cloud / Amazon Lamda)
- web scraping  experience
- machine learning experience
- data visualization experience (Tableau)

### Relevant Experiences

- web development
- mobile development

## About Our company

sMedia is North America’s leading digital technology company for automotive dealerships. Over 450+ dealers partner with sMedia to build traffic, maximize engagement, and drive leads and sales.

## How to apply

Please send an email to [stephanie@smedia.ca](stephanie@smedia.ca) with your resume, use 'React Developer' as subject

---

## Meta

- [ ] Full Time
- [ ] Salary

**Comment by puttputt** [comment]
What are sacks in the game?

**Comment by jphyqr** [comment]
> What are sacks in the game?

meta football joke

**Comment by jphyqr** [comment]
> > What are sacks in the game?
> 
> meta football joke

*SNACKS!!!!
