### ISSUE TITLE
Software Development Instructor - ComIT

### ISSUE THREAD

**Issue by plistingart** [HackRegina/jobs#40]
### Salary Expectation

- $50/hour
- Contract / 3 evenings per week during 3 months

### Location

- Innovation Place, Regina

## What You'll Do _(Job Description)_

Are you a software developer that wants to give back to the community, but don't know how? Do you want to help others by being part of a social, community oriented project?

We’re looking for passionate Ssr/Sr developers that want to make a difference. We’re looking for people who wants to have the chance of contributing to build a world-class social project.

The skills you’ll need:

- Aware of software engineering fundamentals
- Knowledge of NodeJS or React (plus Javascript, HTML, CSS, etc)
- Passion for teaching and mentoring
- Excited about helping others
- Computer Science or Software Engineering degree

People we’re looking for:
- Have a great attitude
- Keep hustling and understand that we are working to help people change their lives
- Understand that helping others is a lifestyle!

Join us to build a worldwide community of people who care about helping others!

### Must Have

- 2+ years working as a NodeJS or React developer
- Experience with mongoDB
- Knowledge of Javascript basics, HTML, CSS, Express

### Relevant Experiences

- Teaching or mentoring
- Lead groups

## About Our company

ComIT is a charity that has been growing at a rapid pace, through more than 20 cities in 3 countries, and with that, we need to expand our elite team of teachers to help more people get a good job in IT.

## How to apply

Please send an email to [info@comit.org](info@comit.org) with your resume, use 'Software Developer Instructor - Regina' as subject

---

## Meta

- [ ] Full Time
- [x] Part Time
- [x] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [ ] Salary

**Comment by LukeTowers** [comment]
@leahcomit @plistingart is this a duplicate of #36?

**Comment by plistingart** [comment]
Hi Luke,
It seems like it is.
I didn't see it and published a new one. Will ask Leah to delete #36

Sorry about that!
