### ISSUE TITLE
SolusGuard - Senior Python / Flask Developer - Anywhere

### ISSUE THREAD

**Issue by bunnyhugdev** [HackRegina/jobs#48]
### Salary Expectation

- $60K to $75K, depending on experience
- Full Time

### Benefits

- Equity in company
- Flexible work hours & arrangements
- Exciting & Fast Paced work!

### Location

- Remote

## What You'll Do _(Job Description)_

Work on our backend microservice based architecture written in Python and Flask. Manage backend infrastructure in AWS using Docker. You may dabble from time to time in front-end code which is primarily angular. You may even touch a mobile app once in a blue moon (if you care to). It's a start-up, you'll have to assume many roles.

### Must Have

- 3+ years working with Python
- experience with Flask
- experience with Git
- familiarity with MongoDB

### Nice to Have

- AWS knowledge (EC2, ECS/ECR, SQS, etc)
- Docker experience
- Experience working on microservice or distributed architectures

### Relevant Experiences

- working remotely
- working at small business or startups

## About Our company

SolusGuard provides safety solutions for companies looking to protect their employees or who may work alone or have some other reason for elevated risk. Our solutions are customizable from top to bottom and may include usage of a proprietary Bluetooth panic button, Check In/Check Out software, realtime monitoring and much more. 

## How to apply

Please send an email to [joel@solusguard.com](joel@solusguard.com) with your resume, use 'Backend Developer' as subject

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [x] Remote OK
- [x] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by DJCrossman** [comment]
Hey Joel, could you update the issue title to follow the format:
`[Company Name] - [Job Title] - [Location]`
