### ISSUE TITLE
SafetyTek - Artificial Intelligence / Machine Learning Developer - Saskatoon

### ISSUE THREAD

**Issue by nehero** [HackRegina/jobs#8]
### Salary Expectation

- $75,000 - $85,000
- Full Time

### Benefits

- Stock options
- Work MacBook
- Health Benefits

### Location

- Saskatoon, SK

## What You'll Do _(Job Description)_

You’ll be on the AI team developing “spence.ai”. Spence is an Artificial Intelligence safety assistant powered by the SafetyTek platform. Using concepts such as pattern recognition, natural language processing/understanding, and optical character recognition to improve SafetyTek’s client experience.

Spence works as a safety assistant in 3 ways.

- By texting him you can ask Spence to do things like, prepare a report, reset a user's password, or check up on a workers training.
- Spence “watches” how your workers use SafetyTek and models their history, then predict when it should expect to see new form submissions. When a rule is broken, Spence can take action by texting the worker to see if they are working on getting the form submission in!
- And Spences vision system component will be able to accept an uploaded safety form and build it into the form library automatically. Spence will also be able to transcribe historical records for you so you have a complete picture of your safety performance.

### Must Have

- Professional experience working on AI/ML projects or personal work that you can show us and talk to us about

### Nice to Have

You'd be a good fit for this position if...

- You're knowledgeable in Python (PHP is a bonus)
- You have built applications utilizing natural language processing, deep learning, pattern recognition, or optical character recognition
- You have mentored junior developers
- You know when to use an existing tool vs when to build your own
- You have an understanding of MVC design patterns
- You have experience building and debugging development environments with Docker
- You have understanding of front-end technologies, such as JavaScript, HTML5, and CSS3
- You have knowledge of Laravel and Angularjs 4
- You understand accessibility and security compliance
- You understand fundamental design principles behind a scalable application
- You understand user authentication and authorization between multiple systems, servers, and environments
- You can integrate multiple data sources and databases into one system
- You can design database schemas that represent and support business processes
- You are proficient with SQL/Neo4j databases and their Cypher query language

### Relevant Experiences

- Artificial Intelligence 
- Machine Learning

## About Our company

SafetyTek is a safety enforcement platform built to assist companies to eliminate work stoppages, reveal the true value of safety, and invest in their reputation. Our platform automatically enforces their safety program by tracking user activity in real-time, creating accountability throughout their workforce, and analyzing trends to predict what should happen in the future. Safety forms and resources are accessed on phones, tablets, and computers and required tasks are completed through the app.

## How to apply

Please send an email to [ozzie.neher@safetytek.ca](ozzie.neher@safetytek.ca) with your resume and tell us a bit about yourself. We look forward to chatting!

---

## Meta

- [x] Full Time
- [ ] Part Time
- [ ] Contract
- [ ] Internship
- [ ] Remote OK
- [ ] Fully Remote
- [ ] Hourly
- [x] Salary

**Comment by LukeTowers** [comment]
@nehero FYI there's a typo on your home page: 

> Never **loose** sight of what is going on in your company.
